Adding makergear config with rewritten / more clear history
The makergear firmware was a hardfork which made it hard to compare
diffs on github.

This branch is all the makergear changes to marlin 1 in a single diff.

Note that this process was not automatic, and might have errors. Be
vigilant!

To produce this branch I:
1. Edited git history to remove diffs that took out marlin files.
   That is, a few commits removed the example configuration files, I added
   those back in by rebasing.

   # find commits with file deletions
   git log --diff-filter=D --stat

   # edit the commit
   git rebase -Xtheirs -i <sha>~1

   # add files back in and roll forward
   git show --no-renames --name-only --format= --diff-filter=D -z | tr \\n \\0 | xargs -0 git checkout HEAD~1 --
   git commit --amend --no-edit --allow-empty
   git rebase --continue

2. Then I started with an upstream branch of marlin 1.1.6 (since this
   was the last version of marlin the makergear branch merged in)

3. I copied the cleaned up makergear files over and then did a little
   cleanup around file permission changes.

So, this branch _should_ show intended changes to marlin. The goal is
that we can 1-1 map these changes to marlin 2.

diff --git a/buildroot/share/git/mfpr b/buildroot/share/git/mfpr
--- a/buildroot/share/git/mfpr
+++ b/buildroot/share/git/mfpr
@@ -5,22 +5,27 @@
 # Make a PR of the current branch against RCBugFix or dev
 #
 
-[[ $# < 2 ]] || { echo "Usage: `basename $0` [branch]" 1>&2 ; exit 1; }
+MFINFO=$(mfinfo "$@") || exit
 
-MFINFO=$(mfinfo "$@") || exit 1
 IFS=' ' read -a INFO <<< "$MFINFO"
+
 ORG=${INFO[0]}
 FORK=${INFO[1]}
 REPO=${INFO[2]}
 TARG=${INFO[3]}
 BRANCH=${INFO[4]}
-OLDBRANCH=${INFO[5]}
 
-[[ $BRANCH == $TARG ]] && { echo "Can't create a PR from the PR Target ($BRANCH). Make a copy first." 1>&2 ; exit 1; }
+if [[ $BRANCH == "(no" ]]; then
+  echo "Git is busy with merge, rebase, etc."
+  exit 1
+fi
 
-[[ $BRANCH != $OLDBRANCH ]] && { git checkout $BRANCH || exit 1; }
+if [[ ! -z "$1" ]]; then { BRANCH=$1 ; git checkout $1 || exit 1; } fi
 
-# See if it's been pushed yet
+if [[ $BRANCH == $TARG ]]; then
+  echo "Can't make a PR from $BRANCH" ; exit
+fi
+
 if [ -z "$(git branch -vv | grep ^\* | grep \\[origin)" ]; then firstpush; fi
 
 TOOL=$(which gnome-open xdg-open open | awk '{ print $1 }')
@@ -33,5 +38,3 @@ else
   echo "Opening a New PR Form..."
   "$TOOL" "$URL"
 fi
-
-[[ $BRANCH != $OLDBRANCH ]] && git checkout $OLDBRANCH
